### ISSUE TITLE
[Marshmallow]古早设备运行即闪退了

### ISSUE THREAD

**Issue by boilfish** [FooIbar/EhViewer#1276]
### 复现步骤 / Step to reproduce

<details><summary>crash-2024-06-04-10-52-06-568.log</summary>

```
TIME=2024-06-04-10-52-06-568

======== PackageInfo ========
PackageName=moe.tarsin.ehviewer.m
VersionName=1.11.6-RC1-M
VersionCode=180056
CommitSha=6d1d737
CommitTime=2024-06-02 15:38

======== DeviceInfo ========
BOARD=ovation
BOOTLOADER=U-Boot_1.1.4
BRAND=Android
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
DEVICE=ovation
DISPLAY=cm_ovation-userdebug 6.0.1 MOB31K 161125 test-keys
FINGERPRINT=Android/cm_ovation/ovation:6.0.1/MOB31K/161125:userdebug/test-keys
HARDWARE=ovation
HOST=gc-xenial
ID=MOB31K
IS_DEBUGGABLE=true
MANUFACTURER=Barnes & Noble
MODEL=BN NookHD+
PRODUCT=cm_ovation
RADIO=unknown
SERIAL=3024300051144300
SUPPORTED_32_BIT_ABIS=armeabi-v7a, armeabi
SUPPORTED_64_BIT_ABIS=
SUPPORTED_ABIS=armeabi-v7a, armeabi
TAGS=test-keys
TIME=1480128242000
TYPE=userdebug
UNKNOWN=unknown
USER=dmaces
ACTIVE_CODENAMES=
BASE_OS=
CODENAME=REL
INCREMENTAL=161125
PREVIEW_SDK_INT=0
RELEASE=6.0.1
RESOURCES_SDK_INT=23
SDK=23
SDK_INT=23
SECURITY_PATCH=2016-11-05
MEMORY=11.8 MiB
MEMORY_NATIVE=12.0 MiB
MEMORY_MAX=256.0 MiB
MEMORY_TOTAL=887.8 MiB

======== CrashInfo ========
java.lang.UnsupportedOperationException: The producer output buffer format 0x5 doesn't match the ImageReader's configured buffer format 0x1.
	at android.media.ImageReader.nativeImageSetup(Native Method)
	at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:327)
	at android.media.ImageReader.acquireNextImage(ImageReader.java:375)
	at android.media.ImageReader.acquireLatestImage(ImageReader.java:277)
	at re0.onImageAvailable(SourceFile:3)
	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:648)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

</details> 

<details><summary>logcat-2024-06-04-10-52.txt</summary>

```
06-04 10:59:09.231   437  1012 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=moe.tarsin.ehviewer.m/com.hippo.ehviewer.ui.MainActivity (has extras)} from uid 10025 on display 0
06-04 10:59:09.350   437  1102 I ActivityManager: Start proc 3303:moe.tarsin.ehviewer.m/u0a90 for activity moe.tarsin.ehviewer.m/com.hippo.ehviewer.ui.MainActivity
06-04 10:59:09.559  3303  3303 D WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
06-04 10:59:09.715  3303  3303 D WM-PackageManagerHelper: Skipping component enablement for androidx.work.impl.background.systemjob.SystemJobService
06-04 10:59:09.715  3303  3303 D WM-Schedulers: Created SystemJobScheduler and enabled SystemJobService
06-04 10:59:10.014  3303  3322 I art     : Note: end time exceeds epoch:
06-04 10:59:10.067  3303  3327 I art     : Note: end time exceeds epoch:
06-04 10:59:10.081  3303  3323 I art     : Rejecting re-init on previously-failed class java.lang.Class<j$.nio.file.attribute.p>
06-04 10:59:10.082  3303  3323 I art     : Rejecting re-init on previously-failed class java.lang.Class<j$.nio.file.attribute.p>
06-04 10:59:10.094  3303  3323 I art     : Rejecting re-init on previously-failed class java.lang.Class<j$.nio.file.attribute.m>
06-04 10:59:10.095  3303  3323 I art     : Rejecting re-init on previously-failed class java.lang.Class<j$.nio.file.attribute.m>
06-04 10:59:10.196  3303  3322 I WebViewFactory: Loading com.google.android.webview version 106.0.5249.126 (code 524912600)
06-04 10:59:10.416  3303  3322 I art     : Rejecting re-init on previously-failed class java.lang.Class<k50>
06-04 10:59:10.416  3303  3322 I art     : Rejecting re-init on previously-failed class java.lang.Class<k50>
06-04 10:59:10.425  3303  3322 I art     : Rejecting re-init on previously-failed class java.lang.Class<k50>
06-04 10:59:10.425  3303  3322 I art     : Rejecting re-init on previously-failed class java.lang.Class<k50>
06-04 10:59:10.444  3303  3322 I cr_WVCFactoryProvider: Loaded version=106.0.5249.126 minSdkVersion=23 isBundle=true multiprocess=false packageId=2
06-04 10:59:10.530  3303  3322 I cr_LibraryLoader: Successfully loaded native library
06-04 10:59:10.531  3303  3322 I cr_CachingUmaRecorder: Flushed 8 samples from 8 histograms.
06-04 10:59:10.591  3303  3327 I art     : Note: end time exceeds epoch:
06-04 10:59:10.625  3303  3348 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: false
06-04 10:59:10.922   437   548 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
06-04 10:59:11.271  3303  3303 W art     : Verification of void LJ.h(Pe0) took 180.389ms
06-04 10:59:11.764  3303  3323 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
06-04 10:59:11.764  3303  3323 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
06-04 10:59:11.764  3303  3323 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
06-04 10:59:11.846  3303  3322 I cr_CronetLibraryLoader: Cronet version: 119.0.6045.31, arch: armv7l
06-04 10:59:11.881  3303  3313 I art     : Background sticky concurrent mark sweep GC freed 11527(1237KB) AllocSpace objects, 1(16KB) LOS objects, 4% free, 12MB/13MB, paused 3.295ms total 143.218ms
06-04 10:59:11.887   437  1019 D ConnectivityService: listenForNetwork for Listen from uid/pid:10090/3303 for NetworkRequest [ id=7, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
06-04 10:59:12.025  3303  3348 W linker  : /system/vendor/lib/hw/gralloc.omap4.so: unused DT entry: type 0xf arg 0x53b
06-04 10:59:12.028  3303  3348 W linker  : /system/vendor/lib/libpvr2d.so: unused DT entry: type 0xf arg 0x767
06-04 10:59:12.042  3303  3348 I OpenGLRenderer: Initialized EGL, version 1.4
06-04 10:59:12.190  3303  3303 I Choreographer: Skipped 91 frames!  The application may be doing too much work on its main thread.
06-04 10:59:12.401  3303  3348 W linker  : /system/vendor/lib/libglslcompiler.so: unused DT entry: type 0xf arg 0x3db
06-04 10:59:13.057  3303  3313 I art     : Background partial concurrent mark sweep GC freed 5727(400KB) AllocSpace objects, 4(120KB) LOS objects, 39% free, 12MB/21MB, paused 640us total 108.703ms
06-04 10:59:13.266  3303  3303 E ImageReader_JNI: Producer output buffer format: 0x5, ImageReader configured format: 0x1
06-04 10:59:13.266  3303  3303 D AndroidRuntime: Shutting down VM
06-04 10:59:13.296  3303  3303 E AndroidRuntime: FATAL EXCEPTION: main
06-04 10:59:13.296  3303  3303 E AndroidRuntime: Process: moe.tarsin.ehviewer.m, PID: 3303
06-04 10:59:13.296  3303  3303 E AndroidRuntime: Theme: themes:{}
06-04 10:59:13.296  3303  3303 E AndroidRuntime: java.lang.UnsupportedOperationException: The producer output buffer format 0x5 doesn't match the ImageReader's configured buffer format 0x1.
06-04 10:59:13.296  3303  3303 E AndroidRuntime:        at android.media.ImageReader.nativeImageSetup(Native Method)
06-04 10:59:13.296  3303  3303 E AndroidRuntime:        at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:327)
06-04 10:59:13.296  3303  3303 E AndroidRuntime:        at android.media.ImageReader.acquireNextImage(ImageReader.java:375)
06-04 10:59:13.296  3303  3303 E AndroidRuntime:        at android.media.ImageReader.acquireLatestImage(ImageReader.java:277)
06-04 10:59:13.296  3303  3303 E AndroidRuntime:        at re0.onImageAvailable(SourceFile:3)
06-04 10:59:13.296  3303  3303 E AndroidRuntime:        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:648)
06-04 10:59:13.296  3303  3303 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-04 10:59:13.296  3303  3303 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
06-04 10:59:13.296  3303  3303 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5461)
06-04 10:59:13.296  3303  3303 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-04 10:59:13.296  3303  3303 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-04 10:59:13.296  3303  3303 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-04 10:59:13.298   437   624 W ActivityManager:   Force finishing activity moe.tarsin.ehviewer.m/com.hippo.ehviewer.ui.MainActivity
06-04 10:59:13.400  3303  3303 I Process : Sending signal. PID: 3303 SIG: 9
06-04 10:59:13.502   437   447 I art     : Background partial concurrent mark sweep GC freed 31350(2MB) AllocSpace objects, 12(476KB) LOS objects, 33% free, 12MB/19MB, paused 1.983ms total 106.567ms
06-04 10:59:13.613   437   451 D GraphicsStats: Buffer count: 5
06-04 10:59:13.613   437  1012 I WindowState: WIN DEATH: Window{df7b2cb u0 moe.tarsin.ehviewer.m/com.hippo.ehviewer.ui.MainActivity}
06-04 10:59:13.616   437  1019 I WindowState: WIN DEATH: Window{d05fb3e u0 moe.tarsin.ehviewer.m}
```

</details> 

### 备注 / Addition details

<details><summary>BN NookHD+ 6.0.1 DeviceInfo</summary>

```
======== DeviceInfo ========
BOARD=ovation
BOOTLOADER=U-Boot_1.1.4
BRAND=Android
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
DEVICE=ovation
DISPLAY=cm_ovation-userdebug 6.0.1 MOB31K 161125 test-keys
FINGERPRINT=Android/cm_ovation/ovation:6.0.1/MOB31K/161125:userdebug/test-keys
HARDWARE=ovation
HOST=gc-xenial
IS_DEBUGGABLE=true
MANUFACTURER=Barnes & Noble
MODEL=BN NookHD+
PRODUCT=cm_ovation
RADIO=unknown
SUPPORTED_32_BIT_ABIS=armeabi-v7a, armeabi
SUPPORTED_64_BIT_ABIS=
SUPPORTED_ABIS=armeabi-v7a, armeabi
TAGS=test-keys
TIME=1480128242000
TYPE=userdebug
UNKNOWN=unknown
USER=dmaces
ACTIVE_CODENAMES=
BASE_OS=
CODENAME=REL
INCREMENTAL=161125
PREVIEW_SDK_INT=0
RELEASE=6.0.1
RESOURCES_SDK_INT=23
SDK=23
SDK_INT=23
SECURITY_PATCH=2016-11-05
MEMORY_TOTAL=887.8 MiB
```

</details> 

### EhViewer 版本号 / EhViewer version code

EhViewer-1.11.6-RC1-marshmallow-armeabi-v7a.apk

### Android 系统版本 / Android version

Android 6.0.1, CyanogenMod 13

### 设备型号 / Device model

BN NookHD+ 平板

### SoC 型号 / Soc model

德仪 OMAP 4

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
1.11.5 是否有这个问题？应该可以直接降级不需要卸载

**Comment by boilfish** [comment]
> 1.11.5 是否有这个问题？应该可以直接降级不需要卸载

测试了一下降级和重装1.11.5，问题还在，logcat里报错是相同的

**Comment by FooIbar** [comment]
> > 1.11.5 是否有这个问题？应该可以直接降级不需要卸载
> 
> 测试了一下降级和重装1.11.5，问题还在，logcat里报错是相同的

升级前的版本是？

**Comment by boilfish** [comment]
> > > 1.11.5 是否有这个问题？应该可以直接降级不需要卸载
> > 
> > 
> > 测试了一下降级和重装1.11.5，问题还在，logcat里报错是相同的
> 
> 升级前的版本是？

我逐版本向前测试吧

**Comment by boilfish** [comment]
> > > 1.11.5 是否有这个问题？应该可以直接降级不需要卸载
> > 
> > 
> > 测试了一下降级和重装1.11.5，问题还在，logcat里报错是相同的
> 
> 升级前的版本是？

经测试是从 21b9fe3cb2f06d2887b6a31f6db9ecd229d6ab02 开始出现闪退的

**Comment by FooIbar** [comment]
这是一个上游的问题，我会向上游报告，在解决之前可以先用旧版
