### ISSUE TITLE
无法下载标题过长的画廊

### ISSUE THREAD

**Issue by UjuiUjuMandan** [FooIbar/EhViewer#1340]
### 复现步骤 / Step to reproduce

0. 设定下载目录
1. 尝试下载 https://e-hentai.org/g/2600568/dd896d7e6b 或者 https://e-hentai.org/g/2943254/91e4973586/

### 预期行为 / Expected behaviour

正常下载。

### 实际行为 / Actual Behaviour

应用崩溃，或者如 UjuiUjuMandan#62 录屏所示。

### 应用日志 / App logs

[log-2024-06-22-01-44-38-718.zip](https://github.com/user-attachments/files/15931158/log-2024-06-22-01-44-38-718.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

0280450

### Android 系统版本 / Android version

LineageOS 21, Android 14

### 设备型号 / Device model

Google Pixel 3

### SoC 型号 / Soc model

Snapdragon 845

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
@FooIbar New crash.

Gallery 1:

```
TIME=2024-06-23-14-23-59-758

======== PackageInfo ========
PackageName=moe.tarsin.ehviewer
VersionName=1.12.0-SNAPSHOT
VersionCode=180056
CommitSha=176a802
CommitTime=2024-06-23 01:04

======== DeviceInfo ========
BOARD=blueline
BOOTLOADER=b1c1-0.4-7617406
BRAND=google
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=blueline
DISPLAY=lineage_blueline-userdebug 14 AP1A.240505.005 eng.root.20240602.215514 dev-keys
FINGERPRINT=google/blueline/blueline:12/SP1A.210812.016.C2/8618562:user/release-keys
HARDWARE=blueline
HOST=d4aa9e59c4b4
ID=AP1A.240505.005
IS_DEBUGGABLE=true
IS_EMULATOR=false
MANUFACTURER=Google
MODEL=Pixel 3
ODM_SKU=G013A
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=blueline
RADIO=unknown
SERIAL=unknown
SKU=G013A
SOC_MANUFACTURER=Qualcomm
SOC_MODEL=SDM845
SUPPORTED_32_BIT_ABIS=armeabi-v7a, armeabi
SUPPORTED_64_BIT_ABIS=arm64-v8a
SUPPORTED_ABIS=arm64-v8a, armeabi-v7a, armeabi
TAGS=dev-keys
TIME=1717365313000
TYPE=userdebug
UNKNOWN=unknown
USER=root
ACTIVE_CODENAMES=
BASE_OS=
CODENAME=REL
INCREMENTAL=eng.root.20240602.215514
KNOWN_CODENAMES={HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair}
MEDIA_PERFORMANCE_CLASS=0
PREVIEW_SDK_FINGERPRINT=REL
PREVIEW_SDK_INT=0
RELEASE=14
RELEASE_OR_CODENAME=14
RELEASE_OR_PREVIEW_DISPLAY=14
SDK=34
SDK_INT=34
SECURITY_PATCH=2024-05-05
MEMORY=23.6 MiB
MEMORY_NATIVE=27.2 MiB
MEMORY_MAX=256.0 MiB
MEMORY_TOTAL=3.5 GiB

======== CrashInfo ========
java.lang.IllegalStateException: Failed to create directory: /storage/emulated/0/Pictures/EhViewer/2943254-[Forest Caravan (Forest)] Futanari Onna Kyoushi ga Class no Mesugaki ni Aorarete …ou ni Shite Shimau Ohanashi _ 扶她女教师被班上的雌小鬼嘲讽不小心就将其狂暴雷普给弄成性处理飞机杯人偶的故事 [Chinese] [Hyakkras]
	at KL1.e(Unknown Source:32)
	at Rq1.i(Unknown Source:86)
	at Pq1.s(Unknown Source:12)
	at Tf.j(Unknown Source:8)
	at hN.run(Unknown Source:112)
	at M1.run(Unknown Source:193)
	at Kx1.run(Unknown Source:2)
	at aC.run(Unknown Source:95)
	Suppressed: gL: [Qr1{Cancelling}@d984736, Dispatchers.IO]

```

Gallery 2:

```
TIME=2024-06-23-14-21-22-676

======== PackageInfo ========
PackageName=moe.tarsin.ehviewer
VersionName=1.12.0-SNAPSHOT
VersionCode=180056
CommitSha=176a802
CommitTime=2024-06-23 01:04

======== DeviceInfo ========
BOARD=blueline
BOOTLOADER=b1c1-0.4-7617406
BRAND=google
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=blueline
DISPLAY=lineage_blueline-userdebug 14 AP1A.240505.005 eng.root.20240602.215514 dev-keys
FINGERPRINT=google/blueline/blueline:12/SP1A.210812.016.C2/8618562:user/release-keys
HARDWARE=blueline
HOST=d4aa9e59c4b4
ID=AP1A.240505.005
IS_DEBUGGABLE=true
IS_EMULATOR=false
MANUFACTURER=Google
MODEL=Pixel 3
ODM_SKU=G013A
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=blueline
RADIO=unknown
SERIAL=unknown
SKU=G013A
SOC_MANUFACTURER=Qualcomm
SOC_MODEL=SDM845
SUPPORTED_32_BIT_ABIS=armeabi-v7a, armeabi
SUPPORTED_64_BIT_ABIS=arm64-v8a
SUPPORTED_ABIS=arm64-v8a, armeabi-v7a, armeabi
TAGS=dev-keys
TIME=1717365313000
TYPE=userdebug
UNKNOWN=unknown
USER=root
ACTIVE_CODENAMES=
BASE_OS=
CODENAME=REL
INCREMENTAL=eng.root.20240602.215514
KNOWN_CODENAMES={HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair}
MEDIA_PERFORMANCE_CLASS=0
PREVIEW_SDK_FINGERPRINT=REL
PREVIEW_SDK_INT=0
RELEASE=14
RELEASE_OR_CODENAME=14
RELEASE_OR_PREVIEW_DISPLAY=14
SDK=34
SDK_INT=34
SECURITY_PATCH=2024-05-05
MEMORY=11.4 MiB
MEMORY_NATIVE=23.2 MiB
MEMORY_MAX=256.0 MiB
MEMORY_TOTAL=3.5 GiB

======== CrashInfo ========
java.lang.IllegalArgumentException: Failed to determine if primary:Pictures/EhViewer/2600568-[灯夜工房 (灯ひでかず)] 色情陷阱地下城·那时的女贤者+后日谈 _ Ero Trap Dungeon …エラップダンジョン_そのときの女賢者+囚われの女賢者 (ドラゴンクエストIII) [Chinese][中国翻訳][星月汉化] is child of primary:Pictures/EhViewer: java.io.FileNotFoundException: Failed to canonicalize path Pictures/EhViewer/2600568-[灯夜工房 (灯ひでかず)] 色情陷阱地下城·那时的女贤者+后日谈 _ Ero Trap Dungeon …エラップダンジョン_そのときの女賢者+囚われの女賢者 (ドラゴンクエストIII) [Chinese][中国翻訳][星月汉化]
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:154)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
	at android.content.ContentResolver.query(ContentResolver.java:1229)
	at android.content.ContentResolver.query(ContentResolver.java:1161)
	at android.content.ContentResolver.query(ContentResolver.java:1117)
	at O3.a(Unknown Source:846)
	at Pv1.getValue(Unknown Source:20)
	at rJ1.p(Unknown Source:2)
	at rJ1.e(Unknown Source:0)
	at Rq1.c(Unknown Source:36)
	at rr1.c(Unknown Source:32)
	at rr1.e(Unknown Source:122)
	at rr1.d(Unknown Source:39)
	at xr1.d(Unknown Source:200)
	at wr1.s(Unknown Source:11)
	at Tf.j(Unknown Source:8)
	at hN.run(Unknown Source:112)
	at M1.run(Unknown Source:193)
	at Kx1.run(Unknown Source:2)
	at aC.run(Unknown Source:95)
	Suppressed: gL: [Qr1{Cancelling}@e242f0b, Dispatchers.IO]

```

**Comment by FooIbar** [comment]
删了重下
