### ISSUE TITLE
画廊详情和阅读器页面偶发闪退

### ISSUE THREAD

**Issue by lings03** [FooIbar/EhViewer#1417]
### 复现步骤 / Step to reproduce

收藏列表和画廊阅读器正常浏览

### 预期行为 / Expected behaviour

正常使用

### 实际行为 / Actual Behaviour

闪退

### 应用日志 / App logs

[log-2024-07-13-14-25-58-242.zip](https://github.com/user-attachments/files/16201162/log-2024-07-13-14-25-58-242.zip)

======== CrashInfo ========
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:730)
	at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:621)
	at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:47)
	at Jz1.q(Unknown Source:7)
	at pP1.C(Unknown Source:19)
	at BL.i(Unknown Source:9)
	at lq.f(Unknown Source:351)
	at HE.r(Unknown Source:22)
	at HE.e(Unknown Source:12)
	at Fz1.e(Unknown Source:98)
	at Fz1.a(Unknown Source:0)
	at IE.r(Unknown Source:151)
	at IE.e(Unknown Source:12)
	at yz1.a(Unknown Source:8)
	at Re1.w(Unknown Source:6)
	at FE.r(Unknown Source:43)
	at pg.l(Unknown Source:8)
	at iO.run(Unknown Source:112)
	at xb.run(Unknown Source:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: gM: [pw1{Cancelling}@448efcf, Dispatchers.IO]

### 备注 / Addition details

看日志好像是数据库外键的问题？闪退了好多次但只有一个crash日志

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

c09173d

### Android 系统版本 / Android version

hyperos1.03 安卓14

### 设备型号 / Device model

note12turbo

### SoC 型号 / Soc model

骁龙7+gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
导致出现闪退的步骤？
日志中的数据库插入只会在退出阅读器时执行

**Comment by lings03** [comment]
没进行过什么特殊操作，就是用的从上到下（连续）方式，正常阅读的时候会突然卡住，然后就闪退了，重新启动app以后阅读器缓存的图片，历史记录也都能正常加载

**Comment by lings03** [comment]
[log-2024-07-14-13-53-30-874.zip](https://github.com/user-attachments/files/16215759/log-2024-07-14-13-53-30-874.zip)
今天闪退以后的新日志

**Comment by FooIbar** [comment]
是在退出阅读器的时候崩溃的吗

**Comment by lings03** [comment]
我找了下规律，在主页也能触发，所以应该和收藏无关

从阅读器退出来以后，在画廊详情页面触发返回手势，会100%导致app界面卡住或者卡出白屏，就像这个视频，试了很多次这样操作的确在阅读器界面和详情界面都闪退了一次，但是没法稳定触发闪退
https://github.com/user-attachments/assets/40f69343-94d1-4746-abfc-fcd7fccb6e2a
https://github.com/user-attachments/assets/0d874d6c-7378-45e2-9fc4-44541a84fa15


如果不进入阅读器就不会出现任何问题
https://github.com/user-attachments/assets/2cbdedc5-e408-4cd6-bb9e-ca0c7947cba5

**Comment by FooIbar** [comment]
> 从阅读器退出来以后，在画廊详情页面触发返回手势，会100%导致app界面卡住或者卡出白屏

不同的问题单独开 issue

关于闪退，https://github.com/FooIbar/EhViewer/actions/runs/9926151206/artifacts/1698992126 增加了一些调试日志

**Comment by lings03** [comment]
彻底卸载重装上面哪个版本后，试了两天也没出现一次闪退问题了，可能是我之前更新之前的版本太老有脏数据的问题？
重装以后无法复现也没log，应该不是通性问题，感觉可以先把issue关了
