### ISSUE TITLE
给予应用访问下载文件夹的权限后，打开下载设置立刻闪退，无法读取此前已下载好的漫画，无法获得CI更新

### ISSUE THREAD

**Issue by Leopard2cv** [FooIbar/EhViewer#1686]
### 复现步骤 / Step to reproduce

https://github.com/user-attachments/assets/67c9ec72-3c47-4671-a4f3-3ef97c4d221b

### 预期行为 / Expected behaviour

点击下载设置后正常显示下载设置，在无网络时查看之前下载好的漫画，在检查更新时成功更新

### 实际行为 / Actual Behaviour

点击下载设置后立刻闪退，无法查看之前下载好的画廊，CI更新一直提示失败，如图
![Screenshot_2024-09-27-12-11-37-983_moe tarsin ehv](https://github.com/user-attachments/assets/4428c3e3-873a-4ba1-8f9f-57d284274fbd)

### 应用日志 / App logs

TIME=2024-09-27-03-24-18-315

======== PackageInfo ========
PackageName=moe.tarsin.ehviewer
VersionName=1.12.0
VersionCode=180059
CommitSha=6191ad7
CommitTime=2024-08-19 13:01

======== DeviceInfo ========
BOARD=cepheus
BOOTLOADER=unknown
BRAND=Xiaomi
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
DEVICE=cepheus
DISPLAY=QKQ1.190825.002 test-keys
FINGERPRINT=Xiaomi/cepheus/cepheus:10/QKQ1.190825.002/V12.0.6.0.QFACNXM:user/release-keys
HARDWARE=qcom
HOST=c4-miui-ota-bd070.bj
ID=QKQ1.190825.002
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=Xiaomi
MODEL=MI 9
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=cepheus
RADIO=unknown
SERIAL=unknown
SUPPORTED_32_BIT_ABIS=armeabi-v7a, armeabi
SUPPORTED_64_BIT_ABIS=arm64-v8a
SUPPORTED_ABIS=arm64-v8a, armeabi-v7a, armeabi
TAGS=release-keys
TIME=1607497997000
TYPE=user
UNKNOWN=unknown
USER=builder
ACTIVE_CODENAMES=
BASE_OS=Xiaomi/cepheus/cepheus:10/QKQ1.190825.002/V12.0.5.0.QFACNXM:user/release-keys
CODENAME=REL
FIRST_SDK_INT=28
INCREMENTAL=V12.0.6.0.QFACNXM
PREVIEW_SDK_FINGERPRINT=REL
PREVIEW_SDK_INT=0
RELEASE=10
RESOURCES_SDK_INT=29
SDK=29
SDK_INT=29
SECURITY_PATCH=2020-11-01
MEMORY=16.2 MiB
MEMORY_NATIVE=33.1 MiB
MEMORY_MAX=256.0 MiB
MEMORY_TOTAL=7.3 GiB

======== CrashInfo ========
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.Collections$SingletonList.get(Collections.java:4872)
	at HQ1.t(Unknown Source:60)
	at T2.c(Unknown Source:1020)
	at Lt.g(Unknown Source:45)
	at Lt.c(Unknown Source:8)
	at wg1.e(Unknown Source:109)
	at Lt.d(Unknown Source:45)
	at Lt.e(Unknown Source:8)
	at ku0.e(Unknown Source:67)
	at Lt.d(Unknown Source:45)
	at Lt.e(Unknown Source:8)
	at cR1.a(Unknown Source:14)
	at Lw.p(Unknown Source:73)
	at Yw.m(Unknown Source:34)
	at J91.a(Unknown Source:24)
	at Gw.a(Unknown Source:4)
	at Gw.a(Unknown Source:4)
	at Yw.n(Unknown Source:11)
	at lu0.i(Unknown Source:27)
	at lu0.h(Unknown Source:114)
	at du0.w0(Unknown Source:165)
	at yg1.e(Unknown Source:850)
	at gu0.f(Unknown Source:67)
	at In0.d(Unknown Source:45)
	at Wt0.a(Unknown Source:15)
	at ls1.d(Unknown Source:55)
	at lt1.a(Unknown Source:51)
	at pt1.d(Unknown Source:128)
	at yU0.b(Unknown Source:2)
	at Pt0.G0(Unknown Source:153)
	at Pt0.d(Unknown Source:125)
	at androidx.compose.foundation.layout.o.f(Unknown Source:84)
	at In0.d(Unknown Source:45)
	at androidx.compose.ui.graphics.d.l(Unknown Source:0)
	at qt0.d(Unknown Source:27)
	at Wt0.a(Unknown Source:15)
	at ls1.d(Unknown Source:55)
	at lt1.a(Unknown Source:51)
	at pt1.d(Unknown Source:128)
	at yU0.b(Unknown Source:2)
	at Pt0.G0(Unknown Source:153)
	at Pt0.d(Unknown Source:125)
	at androidx.compose.animation.u.f(Unknown Source:23)
	at In0.d(Unknown Source:45)
	at androidx.compose.animation.q0.l(Unknown Source:57)
	at qt0.d(Unknown Source:27)
	at li.l(Unknown Source:0)
	at qt0.d(Unknown Source:27)
	at androidx.compose.animation.d.c(Unknown Source:8)
	at mt0.l(Unknown Source:7)
	at qt0.d(Unknown Source:27)
	at Wt0.a(Unknown Source:15)
	at ls1.d(Unknown Source:55)
	at lt1.a(Unknown Source:51)
	at pt1.d(Unknown Source:128)
	at yU0.b(Unknown Source:2)
	at Pt0.G0(Unknown Source:153)
	at Pt0.d(Unknown Source:125)
	at androidx.compose.animation.n.f(Unknown Source:59)
	at In0.d(Unknown Source:45)
	at Wt0.a(Unknown Source:15)
	at ls1.d(Unknown Source:113)
	at lt1.a(Unknown Source:51)
	at pt1.d(Unknown Source:128)
	at yU0.b(Unknown Source:2)
	at Pt0.G0(Unknown Source:153)
	at qG0.b(Unknown Source:43)
	at qG0.m(Unknown Source:107)
	at qG0.j(Unknown Source:98)
	at androidx.compose.ui.platform.x.u(Unknown Source:33)
	at androidx.compose.ui.platform.x.dispatchDraw(Unknown Source:12)
	at android.view.View.draw(View.java:21631)
	at android.view.View.updateDisplayListIfDirty(View.java:20497)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20457)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20457)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20457)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20457)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20457)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20457)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3716)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3511)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2848)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1801)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7795)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

### 备注 / Addition details

更新CI版本后出现的问题，闪退后尝试过回滚版本再次更新，但无法获得CI更新
另：有没有好心人告知一下默认的下载目录名称或者如何寻找下载目录，想为已经下载好但无法读取的做个备份。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

6191ad7

### Android 系统版本 / Android version

MIUI 12.0.6

### 设备型号 / Device model

MI9

### SoC 型号 / Soc model

高通骁龙855

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
没有默认下载目录，需要先设置下载目录，你之前设置的是什么

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/actions/runs/11070014567/artifacts/1987160960
安装这个版本重新设置下载目录，不要选“下载”，在“内部存储空间”里新建一个文件夹

**Comment by Leopard2cv** [comment]
非常感谢，已经可以打开下载设置了。可惜已经下好的本子再也读取不了了。请问一下，下了本子以后是根据什么规则命名对应的储存文件？我或许可以尝试找一下

**Comment by FooIbar** [comment]
你之前的下载目录是什么？
/sdcard/Android/data/moe.tarsin.ehviewer/files/download 里有没有文件？

**Comment by Leopard2cv** [comment]
非常感谢，全部文件都在/sdcard/Android/data/moe.tarsin.ehviewer/files/download这个目录下，已经备份了。得救了。
