### ISSUE TITLE
Can't parse user config

### ISSUE THREAD

**Issue by UjuiUjuMandan** [FooIbar/EhViewer#1723]
### 复现步骤 / Step to reproduce

0. 登录
1. 看着日志

### 预期行为 / Expected behaviour

还不知道这个出错的 fun 是干嘛的...

### 实际行为 / Actual Behaviour

都工作，只是日志里出错而已。

### 应用日志 / App logs

```
com.hippo.ehviewer.client.exception.EhException: 解析失败
	at com.hippo.ehviewer.client.EhEngineKt.rethrowExactly(EhEngine.kt:141)
	at com.hippo.ehviewer.client.EhEngine$getUConfig$lambda$11$$inlined$fetchUsingAsByteBuffer$1.invokeSuspend(EhRequestBuilder.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
Caused by: com.hippo.ehviewer.client.exception.ParseException: Can't parse user config
	at com.hippo.ehviewer.client.parser.UserConfigParser.parse-IoAF18A(UserConfigParser.kt:14)
	at com.hippo.ehviewer.client.EhEngine$getUConfig$lambda$11$$inlined$fetchUsingAsByteBuffer$1.invokeSuspend(EhRequestBuilder.kt:112)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101) 
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113) 
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707) 
Caused by: java.lang.IllegalStateException: Check failed.
	at com.hippo.ehviewer.Settings$stringArrayPref$1.setValue(Settings.kt:263)
	at com.hippo.ehviewer.Settings.setFavCat(Settings.kt:109)
	at com.hippo.ehviewer.client.parser.UserConfigParser.parse-IoAF18A(UserConfigParser.kt:12)
	at com.hippo.ehviewer.client.EhEngine$getUConfig$lambda$11$$inlined$fetchUsingAsByteBuffer$1.invokeSuspend(EhRequestBuilder.kt:112) 
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101) 
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113) 
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707) 

```

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.13.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

2c0d621

### Android 系统版本 / Android version

Android 14

### 设备型号 / Device model

NA

### SoC 型号 / Soc model

NA

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
首次访问 https://exhentai.org/uconfig.php 时会被重定向到论坛获取 igneous
