### ISSUE TITLE
请求增加默认的下载路径

### ISSUE THREAD

**Issue by zanjie1999** [FooIbar/EhViewer#1735]
### 复现步骤 / Step to reproduce

在 下载 中点击 下载路径 ，应用程序闪退

### 预期行为 / Expected behaviour

使用第三方文件管理器选择路径

### 实际行为 / Actual Behaviour

因为没有DocumentsUI，闪退了

### 应用日志 / App logs

```
--------- beginning of crash
10-15 22:48:17.454  4530  4530 E AndroidRuntime: FATAL EXCEPTION: main
10-15 22:48:17.454  4530  4530 E AndroidRuntime: Process: moe.tarsin.ehviewer, PID: 4530
10-15 22:48:17.454  4530  4530 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1937)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4514)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at ib.startActivityForResult(SourceFile:2)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at o2.N(Unknown Source:0)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at Cu.b(Unknown Source:167)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at J2.b(Unknown Source:25)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at HK0.b(Unknown Source:6)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at d3.b(Unknown Source:1442)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at vQ1.b(Unknown Source:7)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at androidx.compose.foundation.n.invoke(Unknown Source:12)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at OI1.s(Unknown Source:157)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at ug.h(Unknown Source:8)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at FZ1.A(Unknown Source:80)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at En.r(Unknown Source:100)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at En.E(Unknown Source:32)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at En.h(Unknown Source:16)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at lH1.h1(Unknown Source:50)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at lH1.V(Unknown Source:31)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at U.V(Unknown Source:115)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at UU0.e(Unknown Source:156)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at UU0.e(Unknown Source:135)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at UU0.e(Unknown Source:135)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at UU0.e(Unknown Source:135)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at UU0.e(Unknown Source:135)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at UU0.e(Unknown Source:135)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at UU0.e(Unknown Source:135)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at Qm0.b(Unknown Source:29)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at c81.a(Unknown Source:119)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at androidx.compose.ui.platform.x.M(Unknown Source:80)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at androidx.compose.ui.platform.x.k(Unknown Source:320)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at androidx.compose.ui.platform.x.dispatchTouchEvent(Unknown Source:75)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2975)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2975)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2975)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2975)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2975)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2975)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.app.Activity.dispatchTouchEvent(Activity.java:3334)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at Hb.dispatchTouchEvent(Unknown Source:2)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.View.dispatchPointerEvent(View.java:12015)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5087)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4901)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4439)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4492)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4458)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4466)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4439)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4492)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4458)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4466)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4439)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6953)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6927)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6888)
10-15 22:48:17.454  4530  4530 E AndroidRuntime:        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7056)
10-15 22:48:17.455  4530  4530 E AndroidRuntime:        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
10-15 22:48:17.455  4530  4530 E AndroidRuntime:        at android.os.MessageQueue.nativePollOnce(Native Method)
10-15 22:48:17.455  4530  4530 E AndroidRuntime:        at android.os.MessageQueue.next(MessageQueue.java:325)
10-15 22:48:17.455  4530  4530 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:142)
10-15 22:48:17.455  4530  4530 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
10-15 22:48:17.455  4530  4530 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-15 22:48:17.455  4530  4530 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
10-15 22:48:17.455  4530  4530 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### 备注 / Addition details

请求增加默认下载路径，可以是/sdcard/Android/包名/data中的目录 （即使用 `getExternalFilesDir(null)` 中的应用程序数据目录）这目录可以直接读写无需授权
因为这些安卓系统的墨水屏设备总会把DocumentsUI给砍了，导致无法使用android.intent.action.OPEN_DOCUMENT_TREE去打开文件管理器选择目录，导致无法下载

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.1

### EhViewer CI 版本 / EhViewer CI Version

32b8686

### Android 系统版本 / Android version

8.0

### 设备型号 / Device model

天喻墨学 M2

### SoC 型号 / Soc model

RK PX30

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
最新 CI 版本在没有 DocumentsUI 时会创建 EhViewer 文件夹作为默认下载目录，不过只适用于 Android 10 以下的设备
