### ISSUE TITLE
测试版本80ad749，尝试通过画廊的“新版本可以”跳转至新画廊时FC

### ISSUE THREAD

**Issue by WeiguangTWK** [FooIbar/EhViewer#309]
### 复现步骤 / Step to reproduce

进入画廊→点击“此画廊有新版本可用”→选择任意新画廊

### 预期行为 / Expected behaviour

正常跳转

### 实际行为 / Actual Behaviour

发生FC

### 应用日志 / App logs

Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Redmi
[Device Model]: 23049RAD8C
[Display]: TKQ1.221114.001 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN
[Process ID]: 17634
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: moe.tarsin.ehviewer
[Version Name]: 1.8.12.0-SNAPSHOT
[Version Code]: 180045
[Target SDK]: 34
[Min SDK]: 28
[Error Type]: JVM
[Crash Time]: 2023-11-23T11:33:25.654
[Stack Trace]:
java.lang.NullPointerException
	at Jg.c(Unknown Source:98)
	at Jg.a(Unknown Source:3244)
	at Jg.m(Unknown Source:290)
	at To.m(Unknown Source:53)
	at Jg.q(Unknown Source:59)
	at Jg.a(Unknown Source:3209)
	at Jg.m(Unknown Source:195)
	at To.m(Unknown Source:53)
	at XB0.E0(Unknown Source:14)
	at Pq.r(Unknown Source:117)
	at Pq.k(Unknown Source:10)
	at ar.o(Unknown Source:33)
	at mE0.a(Unknown Source:50)
	at Nq.a(Unknown Source:4)
	at Nq.a(Unknown Source:4)
	at Nq.a(Unknown Source:4)
	at ar.p(Unknown Source:8)
	at qa0.i(Unknown Source:29)
	at qa0.g(Unknown Source:120)
	at la0.K(Unknown Source:170)
	at Hb0.a(Unknown Source:33)
	at ab0.a(Unknown Source:22)
	at Ta0.b(Unknown Source:51)
	at Ua0.m(Unknown Source:754)
	at Jg.u(Unknown Source:23)
	at Jg.m(Unknown Source:277)
	at na0.b(Unknown Source:79)
	at B50.b(Unknown Source:37)
	at e6.a(Unknown Source:8)
	at e6.k(Unknown Source:13)
	at U90.h(Unknown Source:7)
	at W90.b(Unknown Source:10)
	at e6.a(Unknown Source:37)
	at e6.k(Unknown Source:26)
	at U90.h(Unknown Source:7)
	at W90.b(Unknown Source:10)
	at lP0.h(Unknown Source:0)
	at W90.b(Unknown Source:10)
	at et0.h(Unknown Source:32)
	at W90.b(Unknown Source:10)
	at z61.a(Unknown Source:41)
	at z61.d(Unknown Source:18)
	at pS.c0(Unknown Source:59)
	at fS0.b(Unknown Source:47)
	at gS0.c(Unknown Source:152)
	at Ys0.a(Unknown Source:2)
	at ga0.B0(Unknown Source:99)
	at ga0.b(Unknown Source:95)
	at Hg.b(Unknown Source:111)
	at B50.b(Unknown Source:37)
	at lP0.h(Unknown Source:0)
	at W90.b(Unknown Source:10)
	at z61.a(Unknown Source:41)
	at z61.d(Unknown Source:18)
	at pS.c0(Unknown Source:59)
	at fS0.b(Unknown Source:47)
	at gS0.c(Unknown Source:152)
	at Ys0.a(Unknown Source:2)
	at ga0.B0(Unknown Source:99)
	at ga0.b(Unknown Source:95)
	at J8.d(Unknown Source:0)
	at OI0.a(Unknown Source:930)
	at OI0.m(Unknown Source:11)
	at na0.b(Unknown Source:79)
	at B50.b(Unknown Source:37)
	at z61.a(Unknown Source:41)
	at z61.d(Unknown Source:18)
	at pS.c0(Unknown Source:59)
	at fS0.b(Unknown Source:47)
	at gS0.c(Unknown Source:152)
	at Ys0.a(Unknown Source:2)
	at ga0.B0(Unknown Source:99)
	at ga0.b(Unknown Source:95)
	at Hg.b(Unknown Source:111)
	at B50.b(Unknown Source:37)
	at lP0.h(Unknown Source:0)
	at W90.b(Unknown Source:10)
	at z61.a(Unknown Source:41)
	at z61.d(Unknown Source:18)
	at pS.c0(Unknown Source:59)
	at fS0.b(Unknown Source:47)
	at gS0.c(Unknown Source:152)
	at Ys0.a(Unknown Source:2)
	at ga0.B0(Unknown Source:99)
	at ga0.b(Unknown Source:95)
	at oH0.b(Unknown Source:38)
	at B50.b(Unknown Source:37)
	at z61.a(Unknown Source:41)
	at z61.d(Unknown Source:18)
	at pS.c0(Unknown Source:59)
	at fS0.b(Unknown Source:47)
	at gS0.c(Unknown Source:152)
	at Ys0.a(Unknown Source:2)
	at ga0.B0(Unknown Source:99)
	at Zi0.c(Unknown Source:17)
	at Zi0.m(Unknown Source:17)
	at Zi0.j(Unknown Source:58)
	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(Unknown Source:80)
	at android.view.View.measure(View.java:26640)
	at androidx.compose.ui.platform.a.g(Unknown Source:63)
	at androidx.compose.ui.platform.a.onMeasure(Unknown Source:3)
	at android.view.View.measure(View.java:26640)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7060)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26640)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7060)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26640)
	at D7.onMeasure(Unknown Source:33)
	at android.view.View.measure(View.java:26640)
	at y7.b(Unknown Source:96)
	at B50.b(Unknown Source:37)
	at z61.a(Unknown Source:41)
	at z61.d(Unknown Source:18)
	at pS.c0(Unknown Source:59)
	at fS0.b(Unknown Source:47)
	at gS0.c(Unknown Source:152)
	at Ys0.a(Unknown Source:2)
	at ga0.B0(Unknown Source:99)
	at Zi0.c(Unknown Source:54)
	at Zi0.k(Unknown Source:118)
	at Zi0.h(Unknown Source:76)
	at androidx.compose.ui.platform.AndroidComposeView.y(Unknown Source:33)
	at Ws0.a(Unknown Source:3)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:11)
	at android.view.View.draw(View.java:23414)
	at android.view.View.updateDisplayListIfDirty(View.java:22246)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
	at android.view.View.updateDisplayListIfDirty(View.java:22186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
	at android.view.View.updateDisplayListIfDirty(View.java:22186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
	at android.view.View.updateDisplayListIfDirty(View.java:22186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
	at android.view.View.updateDisplayListIfDirty(View.java:22186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
	at android.view.View.updateDisplayListIfDirty(View.java:22186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
	at android.view.View.updateDisplayListIfDirty(View.java:22186)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4927)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4628)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3816)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2546)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9498)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1467)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
	at android.view.Choreographer.doFrame(Choreographer.java:1003)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1435)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8395)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### 备注 / Addition details

软件自行构建于2023/11/22 UTC+8 23:09

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

80ad749

### Android 系统版本 / Android version

MIUI 14 Android 13

### 设备型号 / Device model

Redmi Note 12 Turbo

### SoC 型号 / Soc model

骁龙7+Gen2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
2023/11/22 UTC+8 23:09 构建的CI版本怎么可能是 80ad749
