### ISSUE TITLE
高级搜索(最低等级)导致软件崩溃

### ISSUE THREAD

**Issue by IZUMI-Zu** [FooIbar/EhViewer#361]
### 复现步骤 / Step to reproduce

https://github.com/FooIbar/EhViewer/assets/23271676/756a955d-7b7d-4e23-ba99-ee133164dc04

### 预期行为 / Expected behaviour

正常打开

### 实际行为 / Actual Behaviour

软件崩溃

### 应用日志 / App logs

[log-2023-11-27-18-05-21-233.zip](https://github.com/FooIbar/EhViewer/files/13472790/log-2023-11-27-18-05-21-233.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.12.0-SNAPSHOT-gms

### EhViewer CI 版本 / EhViewer CI Version

10eda7e

### Android 系统版本 / Android version

ColorOS 12.1

### 设备型号 / Device model

OnePlus 7 pro

### SoC 型号 / Soc model

晓龙 855

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
```
java.lang.IllegalStateException: Offset is unspecified
	at androidx.compose.ui.geometry.InlineClassHelperKt.throwIllegalStateException(InlineClassHelper.kt:35)
	at androidx.compose.ui.geometry.Offset.getX-impl(Offset.kt:355)
	at androidx.compose.ui.unit.IntOffsetKt.minus-Nv-tHpc(IntOffset.kt:170)
	at androidx.compose.ui.node.NodeCoordinator.fromParentPosition-MK-Hz9U(NodeCoordinator.kt:910)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:860)
	at androidx.compose.ui.node.NodeCoordinator.localPositionOf-R5De75A(NodeCoordinator.kt:772)
	at androidx.compose.ui.node.NodeCoordinator.windowToLocal-MK-Hz9U(NodeCoordinator.kt:741)
	at androidx.compose.foundation.text.selection.SelectionManagerKt.visibleBounds(SelectionManager.kt:972)
	at androidx.compose.foundation.text.selection.TextFieldSelectionManagerKt.isSelectionHandleInVisibleBound(TextFieldSelectionManager.kt:952)
	at androidx.compose.foundation.text.CoreTextFieldKt$CoreTextField$onPositionedModifier$1.invoke(CoreTextField.kt:433)
	at androidx.compose.foundation.text.CoreTextFieldKt$CoreTextField$onPositionedModifier$1.invoke(CoreTextField.kt:416)
	at androidx.compose.ui.layout.OnGloballyPositionedNode.onGloballyPositioned(OnGloballyPositionedModifier.kt:78)
	at androidx.compose.ui.node.LayoutNode.dispatchOnPositionedCallbacks$ui_release(LayoutNode.kt:1099)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:72)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:76)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatch(OnPositionedDispatcher.kt:63)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks(MeasureAndLayoutDelegate.kt:648)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks$default(MeasureAndLayoutDelegate.kt:644)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:991)
	at androidx.compose.ui.node.Owner.measureAndLayout$default(Owner.kt:229)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1240)
	at android.view.View.draw(View.java:23269)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4789)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4500)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3687)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9308)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7966)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```
