### ISSUE TITLE
下载搜索删除闪退

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#715]
### 复现步骤 / Step to reproduce

https://github.com/FooIbar/EhViewer/assets/88327304/99e18423-73a8-41a1-91ec-b0c78381560e

### 预期行为 / Expected behaviour

正常删除

### 实际行为 / Actual Behaviour

闪退

### 应用日志 / App logs

[log-2024-02-12-00-41-46-538.zip](https://github.com/FooIbar/EhViewer/files/14233179/log-2024-02-12-00-41-46-538.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

7ef70aa

### Android 系统版本 / Android version

HarmonyOS 4.0.0.128

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
```
java.lang.IllegalArgumentException: offset(7) is out of bounds [0, 0]
        at androidx.compose.ui.text.MultiParagraph.requireIndexInRangeInclusiveEnd(MultiParagraph.kt:837)
        at androidx.compose.ui.text.MultiParagraph.getCursorRect(MultiParagraph.kt:686)
        at androidx.compose.ui.text.TextLayoutResult.getCursorRect(TextLayoutResult.kt:547)
        at androidx.compose.foundation.text.input.internal.TextLayoutStateKt.bringCursorIntoView(TextLayoutState.kt:261)
        at androidx.compose.foundation.text.input.internal.TextFieldDecoratorModifierNode$onRemeasured$1.invokeSuspend(TextFieldDecoratorModifier.kt:573)
```
