### ISSUE TITLE
程序打开即闪退的情况下怎么备份数据

### ISSUE THREAD

**Issue by z1137** [FooIbar/EhViewer#940]
### 复现步骤 / Step to reproduce

在其他旧手机上试过没有闪退，可能是因为现在这个手机以前换过浏览引擎（记得是换成html）

### 预期行为 / Expected behaviour

正常使用

### 实际行为 / Actual Behaviour

实际闪退

### 应用日志 / App logs

无法找到

### 浏览站点 / Browsing site

ex

### EhViewer 版本号 / EhViewer version code

1.11.2

### EhViewer CI 版本 / EhViewer CI Version

无法得知

### Android 系统版本 / Android version

Magic OS 7.0

### 设备型号 / Device model

荣耀60

### SoC 型号 / Soc model

778G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
崩溃日志在 Android/data/moe.tarsin.ehviewer/files/crash 下，复制出来看看
如果访问不了 Android/data 可以用 https://github.com/zhanghai/MaterialFiles

**Comment by z1137** [comment]
TIME=2024-03-22-15-06-26-015

======== PackageInfo ========
PackageName=moe.tarsin.ehviewer
VersionName=1.11.2
VersionCode=180053
CommitSha=6a64ff5
BuildTime=2024/03/17 06:46

======== DeviceInfo ========
BOARD=LSA
BOOTLOADER=unknown
BRAND=HONOR
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=HNLSA
DISPLAY=LSA-AN00 7.0.0.181(C00E175R7P4)
FINGERPRINT=HONOR/LSA-AN00/HNLSA:12/HONORLSA-AN00/7.0.0.181C00:user/release-keys
FINGERPRINTEX=HONOR/LSA-AN00/HNLSA:12/HONORLSA-AN00/7.0.0.181C00:user/release-keys
HARDWARE=qcom
HOST=cn-snxy1c-acf5e5d291707117064538-5f879f6f88-cjwcd
HWFINGERPRINT=///LSA-LGRP1-CHN 7.0.0.181/LSA-AN00-CUST 7.0.0.175(C00)/LSA-AN00-PRELOAD 7.0.0.4(C00R7)//
ID=HONORLSA-AN00
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=HONOR
MODEL=LSA-AN00
ODM_SKU=LSA-AN00
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=LSA-AN00
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=QTI
SOC_MODEL=SM7325
SUPPORTED_32_BIT_ABIS=armeabi-v7a, armeabi
SUPPORTED_64_BIT_ABIS=arm64-v8a
SUPPORTED_ABIS=arm64-v8a, armeabi-v7a, armeabi
TAGS=release-keys
TIME=1707119410000
TYPE=user
UNKNOWN=unknown
USER=test
ACTIVE_CODENAMES=
BASE_OS=
CODENAME=REL
INCREMENTAL=7.0.0.181C00
MEDIA_PERFORMANCE_CLASS=0
PREVIEW_SDK_FINGERPRINT=REL
PREVIEW_SDK_INT=0
RELEASE=12
RELEASE_OR_CODENAME=12
SDK=31
SDK_INT=31
SECURITY_PATCH=2024-02-01
MEMORY=12.5 MiB
MEMORY_NATIVE=16.9 MiB
MEMORY_MAX=384.0 MiB
MEMORY_TOTAL=7.3 GiB

======== CrashInfo ========
java.lang.ExceptionInInitializerError
	at gH.v(Unknown Source:24)
	at rd.r(Unknown Source:8)
	at hB.run(Unknown Source:112)
	at T1.run(Unknown Source:560)
	at MV0.run(Unknown Source:2)
	at ft.run(Unknown Source:95)
	Suppressed: Cz: [jR0{Cancelling}@d28130, Dispatchers.IO]
Caused by: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: _new_GALLERIES.TOKEN (Sqlite code 1299 SQLITE_CONSTRAINT_NOTNULL), (OS error - 2:No such file or directory)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:944)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:776)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:69)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2052)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1962)
	at wT.q(Unknown Source:7)
	at iz.u(Unknown Source:3)
	at Di0.a(Unknown Source:128)
	at x9.t(Unknown Source:163)
	at zT.onUpgrade(Unknown Source:14)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:432)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:328)
	at zT.g(Unknown Source:4)
	at zT.m(Unknown Source:63)
	at zT.b(Unknown Source:23)
	at AT.D0(Unknown Source:9)
	at eG0.c(Unknown Source:10)
	at KD.call(Unknown Source:134)
	at xt.v(Unknown Source:9)
	at rd.r(Unknown Source:8)
	at hB.run(Unknown Source:112)
	at p5.run(Unknown Source:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:930)
android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: _new_GALLERIES.TOKEN (Sqlite code 1299 SQLITE_CONSTRAINT_NOTNULL), (OS error - 2:No such file or directory)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:944)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:776)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:69)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2052)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1962)
	at wT.q(Unknown Source:7)
	at iz.u(Unknown Source:3)
	at Di0.a(Unknown Source:128)
	at x9.t(Unknown Source:163)
	at zT.onUpgrade(Unknown Source:14)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:432)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:328)
	at zT.g(Unknown Source:4)
	at zT.m(Unknown Source:63)
	at zT.b(Unknown Source:23)
	at AT.D0(Unknown Source:9)
	at eG0.c(Unknown Source:10)
	at KD.call(Unknown Source:134)
	at xt.v(Unknown Source:9)
	at rd.r(Unknown Source:8)
	at hB.run(Unknown Source:112)
	at p5.run(Unknown Source:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:930)

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/actions/runs/8387592589/artifacts/1349350510
试下这个
